### ISSUE TITLE
support private members

### ISSUE THREAD

**Issue by christophehurpeau** [esnext/es6-class#3]
See http://wiki.ecmascript.org/doku.php?id=harmony:classes#private_instance_members

**Comment by eventualbuddha** [comment]
Thanks for the contribution! While I like the idea of that feature, it did not actually become part of the current ES6 spec draft. You can see the full draft at http://people.mozilla.org/~jorendorff/es6-draft.html.

**Comment by christophehurpeau** [comment]
Okay, thanks for the link !

**Comment by eventualbuddha** [comment]
Also, you can use something like [private](https://www.npmjs.org/package/private) to add private members to objects (sort of).
